from manim import *
from manim_chemistry import *
from catppuccin import PALETTE

mocha = PALETTE.mocha.colors

class Molecules(Scene):
    def construct(self):
        a = MMoleculeObject.molecule_from_pubchem(name="aspirin")
        b = MMoleculeObject.molecule_from_pubchem(name="benzene")
        c = MMoleculeObject.molecule_from_pubchem(name="caffeine")
        d = MMoleculeObject.molecule_from_pubchem(name="dopamine")
        e = MMoleculeObject.molecule_from_pubchem(name="ethanol")
        f = MMoleculeObject.molecule_from_pubchem(name="fructose")
        g = MMoleculeObject.molecule_from_pubchem(name="glucose")
        h = MMoleculeObject.molecule_from_pubchem(name="histamine")
        i = MMoleculeObject.molecule_from_pubchem(name="ibuprofen")
        j = MMoleculeObject.molecule_from_pubchem(name="juglone")
        k = MMoleculeObject.molecule_from_pubchem(name="ketamine")
        l = MMoleculeObject.molecule_from_pubchem(name="lysine")
        m = MMoleculeObject.molecule_from_pubchem(name="methane")
        n = MMoleculeObject.molecule_from_pubchem(name="nicotine")
        o = MMoleculeObject.molecule_from_pubchem(name="oxytocin")
        p = MMoleculeObject.molecule_from_pubchem(name="penicillin")
        q = MMoleculeObject.molecule_from_pubchem(name="quinine")
        r = MMoleculeObject.molecule_from_pubchem(name="retinol")
        s = MMoleculeObject.molecule_from_pubchem(name="serotonin")
        t = MMoleculeObject.molecule_from_pubchem(name="testosterone")
        u = MMoleculeObject.molecule_from_pubchem(name="uracil")
        v = MMoleculeObject.molecule_from_pubchem(name="vanillin")
        w = MMoleculeObject.molecule_from_pubchem(name="warfarin")
        x = MMoleculeObject.molecule_from_pubchem(name="xylose")
        y = MMoleculeObject.molecule_from_pubchem(name="yohimbine")
        z = MMoleculeObject.molecule_from_pubchem(name="zeaxanthin")

        a1 = Text("Aspirin", color=mocha.text.hex)
        b1 = Text("Benzene", color=mocha.text.hex)
        c1 = Text("Caffeine", color=mocha.text.hex)
        d1 = Text("Dopamine", color=mocha.text.hex)
        e1 = Text("Ethanol", color=mocha.text.hex)
        f1 = Text("Fructose", color=mocha.text.hex)
        g1 = Text("Glucose", color=mocha.text.hex)
        h1 = Text("Histamine", color=mocha.text.hex)
        i1 = Text("Ibuprofen", color=mocha.text.hex)
        j1 = Text("Juglone", color=mocha.text.hex)
        k1 = Text("Ketamine", color=mocha.text.hex)
        l1 = Text("Lysine", color=mocha.text.hex)
        m1 = Text("Methane", color=mocha.text.hex)
        n1 = Text("Nicotine", color=mocha.text.hex)
        o1 = Text("Oxytocin", color=mocha.text.hex)
        p1 = Text("Penicillin", color=mocha.text.hex)
        q1 = Text("Quinine", color=mocha.text.hex)
        r1 = Text("Retinol", color=mocha.text.hex)
        s1 = Text("Serotonin", color=mocha.text.hex)
        t1 = Text("Testosterone", color=mocha.text.hex)
        u1 = Text("Uracil", color=mocha.text.hex)
        v1 = Text("Vanillin", color=mocha.text.hex)
        w1 = Text("Warfarin", color=mocha.text.hex)
        x1 = Text("Xylose", color=mocha.text.hex)
        y1 = Text("Yohimbine", color=mocha.text.hex)
        z1 = Text("Zeaxanthin", color=mocha.text.hex)

        self.play(FadeIn(a), Write(a1.to_edge(UP)))
        self.play(Transform(a, b), Transform(a1, b1.to_edge(UP)))
        self.play(Transform(a, c), Transform(a1, c1.to_edge(UP)))
        self.play(Transform(a, d), Transform(a1, d1.to_edge(UP)))
        self.play(Transform(a, e), Transform(a1, e1.to_edge(UP)))
        self.play(Transform(a, f), Transform(a1, f1.to_edge(UP)))
        self.play(Transform(a, g), Transform(a1, g1.to_edge(UP)))
        self.play(Transform(a, h), Transform(a1, h1.to_edge(UP)))
        self.play(Transform(a, i), Transform(a1, i1.to_edge(UP)))
        self.play(Transform(a, j), Transform(a1, j1.to_edge(UP)))
        self.play(Transform(a, k), Transform(a1, k1.to_edge(UP)))
        self.play(Transform(a, l), Transform(a1, l1.to_edge(UP)))
        self.play(Transform(a, m), Transform(a1, m1.to_edge(UP)))
        self.play(Transform(a, n), Transform(a1, n1.to_edge(UP)))
        self.play(Transform(a, o), Transform(a1, o1.to_edge(UP)))
        self.play(Transform(a, p), Transform(a1, p1.to_edge(UP)))
        self.play(Transform(a, q), Transform(a1, q1.to_edge(UP)))
        self.play(Transform(a, r), Transform(a1, r1.to_edge(UP)))
        self.play(Transform(a, s), Transform(a1, s1.to_edge(UP)))
        self.play(Transform(a, t), Transform(a1, t1.to_edge(UP)))
        self.play(Transform(a, u), Transform(a1, u1.to_edge(UP)))
        self.play(Transform(a, v), Transform(a1, v1.to_edge(UP)))
        self.play(Transform(a, w), Transform(a1, w1.to_edge(UP)))
        self.play(Transform(a, x), Transform(a1, x1.to_edge(UP)))
        self.play(Transform(a, y), Transform(a1, y1.to_edge(UP)))
        self.play(Transform(a, z), Transform(a1, z1.to_edge(UP)))
        self.wait()
        self.play(Unwrite(a), Unwrite(a1))